spring.application.name=chess-notes-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/chess_notes
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update